---
version: "3.7"
services:
  app:
    image: "barrelmaker97/friendbot:latest"
    container_name: friendbot
    ports:
      - "6000:6000"
    volumes:
      - type: bind
        source: ${FB_EXPORT}
        target: /export.zip
        read_only: true
    restart: always
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
