# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls behave
        pip install -r requirements.txt
    - name: Run Tests
      env:
        EXPORT_ZIP: ./test_data/export.zip
        SLACK_SIGNING_SECRET: abcdef12345abcdef12345abcdef1234
      run: coverage run --source="./friendbot" -m behave
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls
